"use client";

import { useEffect } from 'react';
import Head from 'next/head';
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    // Dynamically import AOS to ensure it loads on the client-side
    import("aos").then(AOS => {
      AOS.init();
    });
  }, []);

  return (
    <html lang="en">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@next/dist/aos.css" />
      </Head>
      <body className={inter.className}>
        {children}
        <script src="https://cdn.jsdelivr.net/npm/aos@next/dist/aos.js" defer></script>
      </body>
    </html>
  );
}

